steps:
- checkout: git://$(Build.Repository.Name)/$(Build.Repository.Id)
  fetchDepth: 0
  persistCredentials: true

- script: |
    # Configuração essencial
    git config --global user.email "azure-pipeline@example.com"
    git config --global user.name "Azure Pipeline"
    
    # Mostra o estado atual para debug
    echo "=== ESTADO INICIAL ==="
    git status
    git branch -a
    git remote -v
    ls -la
    
    # Configura autenticação com GitHub usando PAT
    git remote add github https://$(GITHUB_PAT)@github.com/wesleykalb/MyRecipeBook.git
    
    # Renomeia a branch atual para develop se necessário
    git checkout -b develop 2>/dev/null || git checkout develop
    
    # Sincroniza com o repositório GitHub
    git fetch github
    
    # Faz push de TUDO para o GitHub (forçado se necessário)
    git push --force --tags github
    git push github --mirror
    
    # Verificação final
    echo "=== ESTADO FINAL ==="
    git status
    git branch -a
    git remote -v
    ls -la
  env:
    GITHUB_PAT: $(GITHUB_PAT)  # Certifique-se que esta variável está definida nas variáveis do pipeline
  displayName: 'Push Completo para GitHub'