steps:
- checkout: git://$(Build.Repository.Name)/$(Build.Repository.Id
  fetchDepth: 0
  persistCredentials: true  # Mantém as credenciais para operações posteriores

- script: |
    # Configuração essencial
    git config --global user.email "azure-pipeline@example.com"
    git config --global user.name "Azure Pipeline"
    
    # Mostra o estado atual para debug
    echo "=== ESTADO INICIAL ==="
    git status
    git branch -a
    git remote -v
    
    # Configura autenticação com GitHub
    git config --global credential.helper store
    echo "https://x-access-token:$(GITHUB_PATH)@github.com" > ~/.git-credentials
    
    # Adiciona remote do GitHub
    git remote add github https://github.com/wesleykalb/MyRecipeBook.git
    
    # Sincroniza com o repositório GitHub
    git fetch github
    
    # Garante que estamos na branch develop
    git checkout develop
    
    # Faz push de TUDO para o GitHub
    git push --all github
    git push --tags github
    
    # Verificação final
    echo "=== ESTADO FINAL ==="
    git status
    git branch -a
    ls -la
  env:
    GITHUB_PATH: $(GITHUB_PAT)
  displayName: 'Push Completo para GitHub'