steps:
- checkout: self
  fetchDepth: 0
  persistCredentials: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Configuração essencial
      git config --global user.email "wesleykalb10@gmail.com"
      git config --global user.name "Azure Pipeline"
      
      # Criar branch develop local
      git checkout -b develop origin/develop
      echo "Testando token..."
      curl -s -H "Authorization: token $GIT_TOKEN" https://api.github.com/user | grep login
      
      # Configurar autenticação com arquivo de credenciais
      echo "https://$GIT_TOKEN:x-oauth-basic@github.com" > ~/.git-credentials
      git config --global credential.helper store
      
      # Adicionar remote do GitHub (com autenticação embutida)
      git remote add github https://$GIT_TOKEN@github.com/wesleykalb/MyRecipeBook.git
      
      # Forçar push da branch develop
      echo "=== ENVIANDO ARQUIVOS ==="
      git push github develop:develop --force
      
      # Verificação final
      echo "=== VERIFICAÇÃO ==="
      git ls-remote --heads github
      echo "=== SUCESSO ==="
  env:
      GIT_TOKEN: $(GITHUB_PAT)  # Variável segura definida no pipeline
  displayName: 'Push para GitHub'