steps:
- checkout: self
  fetchDepth: 0
  persistCredentials: true

- script: |
    # Configuração básica
    git config --global user.email "wesleykalb10@gmail.com"
    git config --global user.name "Seu Nome"
    
    # Sincronizar branch develop
    git checkout -b develop origin/develop
    
    # Configurar remote do GitHub
    git remote add github https://$(GITHUB_PAT)@github.com/wesleykalb/MyRecipeBook.git
    
    # Forçar push (substitui tudo no GitHub pelo conteúdo do Azure)
    echo "Enviando arquivos para GitHub..."
    git push --force github develop:develop
    
    # Verificação
    echo "=== ARQUIVOS ENVIADOS ==="
    git ls-remote --heads github
    echo "=== SUCESSO ==="
  env:
    GITHUB_PAT: $(GITHUB_PAT)
  displayName: 'Sincronizar Azure → GitHub'