steps:
- checkout: git://$(Build.Repository.Name)/$(Build.Repository.Id)  # Checkout do Azure Repos
  fetchDepth: 0  # Pega todo o histórico

- script: |
    # Configuração do Git
    git config --global user.email "wesleykalb@gmail.com"
    git config --global user.name "Azure Pipeline"
    
    # Mostra branches existentes (para debug)
    git branch -a
    
    # Configura autenticação com GitHub
    echo "https://x-access-token:$GITHUB_TOKEN@github.com" > ~/.git-credentials
    git config --global credential.helper store
    
    # Adiciona remote do GitHub
    git remote add github https://github.com/wesleykalb/MyRecipeBook.git
    
    # Faz push forçado da develop (cria a branch remota se não existir)
    git push --force github develop:develop
    
    # Mostra resultado
    git remote -v
    git branch -a
  env:
    GITHUB_TOKEN: $(GITHUB_PAT)  # Usando nome mais compatível
  displayName: 'Push para GitHub'
