steps:
- checkout: self
  fetchDepth: 0
  persistCredentials: true

- script: |
    # Configuração essencial
    git config --global user.email "wesleykalb10@gmail.com"
    git config --global user.name "Azure Pipeline"
    
    # Criar branch develop local a partir da origin/develop
    git checkout -b develop origin/develop
    
    # Adicionar remote do GitHub COM autenticação
    git remote add github https://$(GITHUB_PAT)@github.com/wesleykalb/MyRecipeBook.git
    
    # Forçar push somente da branch develop
    git push github develop --force
    
    # Verificação
    echo "=== ARQUIVOS ENVIADOS ==="
    git ls-remote --heads github
    echo "=== SUCESSO ==="
  displayName: 'Sincronizar Develop com GitHub'