steps:
- checkout: self
  fetchDepth: 0
  persistCredentials: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Configurações essenciais
      git config --global user.email "azure-pipeline@example.com"
      git config --global user.name "Azure Pipeline"
      
      # Debug inicial
      echo "=== ESTADO INICIAL ==="
      git status
      git branch -a
      git remote -v
      ls -la
      
      # Configurar autenticação com GitHub
      echo "Configurando autenticação..."
      git config --global credential.helper store
      echo "https://$(GITHUB_TOKEN):x-oauth-basic@github.com" > ~/.git-credentials
      
      # Adicionar remote do GitHub
      git remote add github https://github.com/wesleykalb/MyRecipeBook.git
      
      # Forçar push de TUDO para o GitHub
      echo "Executando push para GitHub..."
      git push --mirror github
      
      # Verificação final
      echo "=== ARQUIVOS ENVIADOS ==="
      git ls-remote --heads github
      echo "=== OPERAÇÃO CONCLUÍDA COM SUCESSO ==="
  env:
      GITHUB_TOKEN: $(GITHUB_PAT)
  displayName: 'Push Completo para GitHub'